springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
server:
  port: ${SERVER_PORT}
spring:
  datasource:
    url: ${DB_URL}
    username: ${RDS_USER_NAME}
    password: ${RDS_USER_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
weeth:
  jwt:
    key: ${JWT_KEY}
    access:
      expiration: ${ACCESS_EXP}
      header: ${ACCESS_HEAD}
    refresh:
      expiration: ${REFRESH_EXP}
      header: ${REFRESH_HEAD}
cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false