#!/bin/bash
#
# DB 스키마를 덤프하여 references/schema.md에 저장하는 스크립트
#
# 사용법:
#   ./dump-schema.sh                          # 환경변수에서 읽기
#   ./dump-schema.sh -h localhost -P 3306 -u root -p password -d weeth
#
# 환경변수:
#   DB_HOST (default: localhost)
#   DB_PORT (default: 3306)
#   DB_USER (default: root)
#   DB_PASSWORD
#   DB_NAME (default: weeth)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SKILL_DIR="$(dirname "$SCRIPT_DIR")"
OUTPUT_FILE="${SKILL_DIR}/references/schema.md"

# 기본값 (환경변수 또는 기본값)
HOST="${DB_HOST:-localhost}"
PORT="${DB_PORT:-3306}"
USER="${DB_USER:-root}"
PASSWORD="${DB_PASSWORD:-}"
DATABASE="${DB_NAME:-weeth}"

# 인자 파싱
while getopts "h:P:u:p:d:" opt; do
    case $opt in
        h) HOST="$OPTARG" ;;
        P) PORT="$OPTARG" ;;
        u) USER="$OPTARG" ;;
        p) PASSWORD="$OPTARG" ;;
        d) DATABASE="$OPTARG" ;;
        *) echo "Usage: $0 [-h host] [-P port] [-u user] [-p password] [-d database]"; exit 1 ;;
    esac
done

# mysql 클라이언트 확인
if ! command -v mysql &> /dev/null; then
    echo "Error: mysql client not found. Install with: brew install mysql-client"
    exit 1
fi

MYSQL_OPTS="-h ${HOST} -P ${PORT} -u ${USER}"
if [ -n "$PASSWORD" ]; then
    MYSQL_OPTS="${MYSQL_OPTS} -p${PASSWORD}"
fi

echo "Connecting to MySQL ${HOST}:${PORT}/${DATABASE}..."

# 테이블 목록 조회
TABLES=$(mysql ${MYSQL_OPTS} -N -e "
    SELECT TABLE_NAME
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = '${DATABASE}'
      AND TABLE_TYPE = 'BASE TABLE'
    ORDER BY TABLE_NAME;
")

if [ -z "$TABLES" ]; then
    echo "Error: No tables found in database '${DATABASE}'"
    exit 1
fi

TABLE_COUNT=$(echo "$TABLES" | wc -l | tr -d ' ')
echo "Found ${TABLE_COUNT} tables. Dumping schema..."

# 마크다운 출력 시작
{
    echo "# ${DATABASE} DB Schema"
    echo ""
    echo "> Auto-generated by dump-schema.sh at $(date '+%Y-%m-%d %H:%M:%S')"
    echo "> Connection: ${HOST}:${PORT}/${DATABASE}"
    echo ""

    # 테이블 요약
    echo "## Tables (${TABLE_COUNT})"
    echo ""
    echo "| # | Table | Engine | Rows (approx) | Comment |"
    echo "|---|-------|--------|---------------|---------|"

    mysql ${MYSQL_OPTS} -N -e "
        SELECT
            TABLE_NAME,
            ENGINE,
            TABLE_ROWS,
            IFNULL(TABLE_COMMENT, '')
        FROM INFORMATION_SCHEMA.TABLES
        WHERE TABLE_SCHEMA = '${DATABASE}'
          AND TABLE_TYPE = 'BASE TABLE'
        ORDER BY TABLE_NAME;
    " | awk -F'\t' '{printf "| %d | %s | %s | %s | %s |\n", NR, $1, $2, $3, $4}'

    echo ""

    # 각 테이블 상세
    echo "## Table Details"
    echo ""

    for TABLE in $TABLES; do
        echo "### ${TABLE}"
        echo ""

        # 컬럼 정보
        echo "| Column | Type | Nullable | Key | Default | Extra |"
        echo "|--------|------|----------|-----|---------|-------|"

        mysql ${MYSQL_OPTS} -N -e "
            SELECT
                COLUMN_NAME,
                COLUMN_TYPE,
                IS_NULLABLE,
                COLUMN_KEY,
                IFNULL(COLUMN_DEFAULT, 'NULL'),
                EXTRA
            FROM INFORMATION_SCHEMA.COLUMNS
            WHERE TABLE_SCHEMA = '${DATABASE}'
              AND TABLE_NAME = '${TABLE}'
            ORDER BY ORDINAL_POSITION;
        " | awk -F'\t' '{printf "| %s | %s | %s | %s | %s | %s |\n", $1, $2, $3, $4, $5, $6}'

        echo ""

        # 인덱스 정보
        INDEX_COUNT=$(mysql ${MYSQL_OPTS} -N -e "
            SELECT COUNT(DISTINCT INDEX_NAME)
            FROM INFORMATION_SCHEMA.STATISTICS
            WHERE TABLE_SCHEMA = '${DATABASE}'
              AND TABLE_NAME = '${TABLE}';
        ")

        if [ "$INDEX_COUNT" -gt 0 ]; then
            echo "**Indexes:**"
            echo ""
            echo "| Index | Columns | Unique | Type |"
            echo "|-------|---------|--------|------|"

            mysql ${MYSQL_OPTS} -N -e "
                SELECT
                    INDEX_NAME,
                    GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX SEPARATOR ', '),
                    CASE WHEN NON_UNIQUE = 0 THEN 'YES' ELSE 'NO' END,
                    INDEX_TYPE
                FROM INFORMATION_SCHEMA.STATISTICS
                WHERE TABLE_SCHEMA = '${DATABASE}'
                  AND TABLE_NAME = '${TABLE}'
                GROUP BY INDEX_NAME, NON_UNIQUE, INDEX_TYPE
                ORDER BY INDEX_NAME;
            " | awk -F'\t' '{printf "| %s | %s | %s | %s |\n", $1, $2, $3, $4}'

            echo ""
        fi

        # FK 정보
        FK_COUNT=$(mysql ${MYSQL_OPTS} -N -e "
            SELECT COUNT(*)
            FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
            WHERE TABLE_SCHEMA = '${DATABASE}'
              AND TABLE_NAME = '${TABLE}'
              AND REFERENCED_TABLE_NAME IS NOT NULL;
        ")

        if [ "$FK_COUNT" -gt 0 ]; then
            echo "**Foreign Keys:**"
            echo ""
            echo "| Constraint | Column | References |"
            echo "|-----------|--------|------------|"

            mysql ${MYSQL_OPTS} -N -e "
                SELECT
                    CONSTRAINT_NAME,
                    COLUMN_NAME,
                    CONCAT(REFERENCED_TABLE_NAME, '.', REFERENCED_COLUMN_NAME)
                FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
                WHERE TABLE_SCHEMA = '${DATABASE}'
                  AND TABLE_NAME = '${TABLE}'
                  AND REFERENCED_TABLE_NAME IS NOT NULL
                ORDER BY CONSTRAINT_NAME;
            " | awk -F'\t' '{printf "| %s | %s | %s |\n", $1, $2, $3}'

            echo ""
        fi

        echo "---"
        echo ""
    done

    # 관계 다이어그램 (FK 기반)
    FK_TOTAL=$(mysql ${MYSQL_OPTS} -N -e "
        SELECT COUNT(*)
        FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
        WHERE TABLE_SCHEMA = '${DATABASE}'
          AND REFERENCED_TABLE_NAME IS NOT NULL;
    ")

    if [ "$FK_TOTAL" -gt 0 ]; then
        echo "## Relationships"
        echo ""
        echo "\`\`\`"

        mysql ${MYSQL_OPTS} -N -e "
            SELECT
                TABLE_NAME,
                COLUMN_NAME,
                REFERENCED_TABLE_NAME,
                REFERENCED_COLUMN_NAME
            FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
            WHERE TABLE_SCHEMA = '${DATABASE}'
              AND REFERENCED_TABLE_NAME IS NOT NULL
            ORDER BY TABLE_NAME, COLUMN_NAME;
        " | awk -F'\t' '{printf "%s.%s --> %s.%s\n", $1, $2, $3, $4}'

        echo "\`\`\`"
    fi

} > "$OUTPUT_FILE"

echo ""
echo "Schema dumped to: ${OUTPUT_FILE}"
echo "Tables: ${TABLE_COUNT}"
echo "Done."